# Generated by Django 2.2.5 on 2020-03-01 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_user',
            name='classs',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_user',
            name='dept',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_user',
            name='sex',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_user',
            name='tel',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
