# Generated by Django 2.2.5 on 2020-03-10 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20200301_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_user',
            name='password',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
